module.exports = {
	PING_PONG: 1,
	SISTEMA: 2,
	USUARIO_CONECTADO: 4,
	USUARIO_DESCONECTADO: 5,
	LIMPIAR_MENSAJES: 6,
	CHAT_MENSAJE: 10,
	NICK_NAME: 11,
	CHAT_OPEN: 12,
	CHAT_RECEIVED: 13,
	CHAT_FRIEND_INDEX: 14
}